AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Harmony Matcher Lambda function to compare instruments.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: function/.
      Description: Call the Harmony matcher
      Timeout: 20
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active
      Layers:
        - 'arn:aws:lambda:eu-west-2:336392948345:layer:AWSSDKPandas-Python39:6'
      FunctionName: harmony-matcher
Globals:
  Function:
    Environment:
      Variables:
        VECTOR_API_KEY: hfkey
