AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: s3://lambda-artifacts-73327015efb336e8/14a8c0ae0ba6160b28ffc8055715810b
      Description: Call the AWS Lambda API
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      Tracing: Active
      Layers:
      - Ref: libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: blank-python-lib
      Description: Dependencies for the blank-python sample app.
      ContentUri: s3://lambda-artifacts-73327015efb336e8/7374f402771542aa9f1da75059d10712
      CompatibleRuntimes:
      - python3.8
