name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - harmony_fastapi/**
      - .github/workflows/deploy_fastapi_to_azure.yml
  pull_request:
    branches: [ "main" ]
    paths:
      - harmony_fastapi/**
      - .github/workflows/deploy_fastapi_to_azure.yml
    
env:
  IMAGE_NAME: harmonyapi

jobs:

  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Log into registry
      uses: docker/login-action@v1
      with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
    - name: Copy the library in
      run: 'cp -r ../harmony_pypi_package/src/harmony/ ./'
      working-directory: ./harmony_fastapi
    - name: Build & Push
      uses: docker/build-push-action@v2
      with:
          context: ./harmony_fastapi
          push: true
          build-args: |
            version=${{ steps.tag.outputs.tag }}
          tags: regprotocolsfds.azurecr.io/harmonyapi:${{ github.sha }}


  deploy:
    runs-on: ubuntu-latest

    needs: build

    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
        working-directory: ./harmony_fastapi

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: wellcomeharmonyapi
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: regprotocolsfds.azurecr.io/harmonyapi:${{ github.sha }}
