name: Deploy PDF Parser to AWS Lambda (Python)

on:
  push:
    branches: [ "main" ]
    paths:
      - deployment/pdf_processor_tika_lambda_java/**
      - .github/workflows/deploy-pdf-tika-parser-to-aws-lambda.yml
  pull_request:
    branches: [ "main" ]
    paths:
      - deployment/pdf_processor_tika_lambda_java/**
      - .github/workflows/deploy-pdf-tika-parser-to-aws-lambda.yml

jobs:

  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          python-version: '3.9'
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: sam build
        working-directory: ./deployment/pdf_processor_tika_lambda_java

      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name harmony-matcher --resolve-s3 --resolve-image-repos --capabilities CAPABILITY_IAM --region  ${{ secrets.AWS_REGION }}
        working-directory: ./deployment/pdf_processor_tika_lambda_java

