name: Test Pypi package

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
env:
  HARMONY_LITE: no_transformers
          
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.10.11]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
